
# TODO: use osx_defaults task
# - https://github.com/ansible/ansible/issues/19585
- name: Add {{ name }} to dock
  shell: (defaults read com.apple.dock | grep "{{ name }}") ||  defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/{{ name }}.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  register: update_dock_result
  changed_when: name not in update_dock_result.stdout
  notify:
    - restart dock

#- name: Add {{ name }} to dock
#  osx_defaults:
#    array_add: true
#    domain: com.apple.dock
#    key: persistent-apps
#    type: array
#    value:
#      - >
#        <dict>
#          <key>tile-data</key>
#          <dict>
#            <key>file-data</key>
#            <dict>
#              <key>_CFURLString</key>
#              <string>/Applications/{{ name }}.app</string>
#              <key>_CFURLStringType</key>
#              <integer>0</integer>
#            </dict>
#          </dict>
#        </dict>
