
- name: Check dock status
  shell: defaults read com.apple.dock
  changed_when: false
  register: defaults_read_result

- name: Add {{ app }} to dock
  shell: defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/{{ app }}.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  when: defaults_read_result.stdout.find(app) == -1
  changed_when: true
  notify:
    - restart dock

