
- name: Setup /usr/local
  become: true
  file:
    path: /usr/local
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: admin
    mode: 0755

- name: Setup brew src dir
  file:
    path: "{{ brew_src_dir }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: admin
    mode: 0755

- name: Download brew
  get_url:
    url: https://github.com/Homebrew/brew/archive/{{ brew_version }}.tar.gz
    dest: "{{ brew_src_archive }}"
  register: brew_download_result

- name: Extract brew
  unarchive:
    src: "{{ brew_src_archive }}"
    dest: /usr/local/src
    remote_src: yes
  when: brew_download_result.changed

- name: Setup links
  file:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    state: link
  with_items:
    - src: "{{ brew_src_dir }}"
      path: "{{ brew_install_dir }}"
    - src: "{{ brew_install_dir }}/bin/brew"
      path: "{{ brew_bin }}"

- name: Install Cask
  command: "{{ brew_bin }} tap caskroom/cask"
  register: install_cask_result

- name: Install brew required packages
  include: install_package.yml
  vars:
    package: "{{ item }}"
  with_items: "{{ brew_required_packages }}"

- name: Verify brew installation
  command: "{{ brew_bin }} doctor"
  changed_when: false

