
- name: Install brew
  include: install_brew.yml

- name: Install packages
  include: install_package.yml
  vars:
    package: "{{ item }}"
  with_items: "{{ packages }}"

- name: Linkapps
  command: "{{ brew_bin }} linkapps {{ item }}"
  register: brew_linkapps_result
  changed_when: true
  failed_when: 'brew_linkapps_result.stderr != ""'
  with_items: "{{ packages }}"

