
- name: Tap fonts
  homebrew_tap:
    name: caskroom/fonts
    state: present

- name: Install brew packages
  brew:
    name: "{{ item }}"
    state: latest
  with_items:
    - the_silver_searcher

- name: Install cask packages
  cask:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - java
    - font-ubuntu

- name: Install construi
  pip:
    name: construi
    version: 1.0.0rc4
    state: present

- name: Configure ag
  template:
    src: agignore.j2
    dest: "{{ ansible_env.HOME }}/.agignore"


- name: Make project directory
  file:
    path: "{{ ansible_env.HOME }}/Projects"
    state: directory

