
- name: Install brew packages
  brew:
    name: "{{ item }}"
    state: latest
  with_items:
    - the_silver_searcher

- name: Install docker
  cask:
    name: docker
    state: latest

- name: Install construi
  pip:
    name: construi
    version: 44
    state: present

- name: Make project directory
  file:
    path: "{{ ansible_env.HOME }}/Projects"
    state: directory

