
- name: Install brew packages
  brew:
    name: "{{ item }}"
    state: latest
  with_items:
    - the_silver_searcher

- name: Install docker
  cask:
    name: docker
    state: latest

- name: Install construi
  pip:
    name: construi
    version: 1.0.0rc4
    state: present

- name: Configure ag
  template:
    src: agignore.j2
    dest: "{{ ansible_env.HOME }}/.agignore"


- name: Make project directory
  file:
    path: "{{ ansible_env.HOME }}/Projects"
    state: directory

