
# doxygen shouldn't be necessary here, but it's not installed with tmux
# and 'brew doctor' will complain about it missing
- name: Install brew packages
  brew:
    name: "{{ item }}"
    state: latest
  with_items:
    - doxygen
    - tmux

- name: Install iterm2
  cask:
    name: iterm2
    state: latest

- name: dotfiles
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items:
    - bashrc
    - bash_profile
    - profile
    - tmux.conf

- name: iterm hide scrollbar
  shell: "[ $(defaults read com.googlecode.iterm2 HideScrollbar) == 1 ] && echo 'Unchanged.' || defaults write com.googlecode.iterm2 HideScrollbar 1"
  register: iterm_preference_result
  changed_when: "'Unchanged' not in iterm_preference_result.stdout"

- name: iterm profile
  template:
    src: iterm.profile.j2
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/locala.profile"


