
# doxygen shouldn't be necessary here, but it's not installed with tmux
# and 'brew doctor' will complain about it missing
- name: Install brew packages
  brew:
    name: "{{ item }}"
    state: latest
  with_items:
    - doxygen
    - tmux

- name: Install iterm2
  cask:
    name: iterm2
    state: latest

- name: Install tmux-better-mouse-mode
  git:
    repo: https://github.com/nhdaly/tmux-better-mouse-mode
    dest: "{{ tmux_plugin_src_dir }}/tmux-better-mouse-mode"
    version: 4c686e5a1f381e072b102df63f3f8a17426fb107

- name: dotfiles
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items:
    - bashrc
    - bash_profile
    - profile
    - tmux.conf

- name: iterm hide scrollbar
  osx_defaults:
    domain: com.googlecode.iterm2
    key: HideScrollbar
    value: 1

- name: iterm profile
  template:
    src: iterm.profile.j2
    dest: "{{ ansible_env.HOME }}/Library/Application Support/iTerm2/DynamicProfiles/locala.profile"


