
- name: Install tmux-better-mouse-mode
  git:
    repo: https://github.com/nhdaly/tmux-better-mouse-mode
    dest: "{{ tmux_plugin_src_dir }}/tmux-better-mouse-mode"
    version: 4c686e5a1f381e072b102df63f3f8a17426fb107

- name: dotfiles
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items:
    - bashrc
    - bash_profile
    - profile
    - tmux.conf

- name: alacritty config
  template:
    src: alacritty.yml.j2
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"

