
- name: Install apps
  brew:
    name: "{{ item }}"
    state: latest
  with_items:
    - koekeishiya/formulae/khd
    - koekeishiya/formulae/kwm

- name: kwm config directory
  file:
    path: "{{ ansible_env.HOME }}/.kwm"
    state: directory

- name: kwm dotfile
  template:
    src: kwmrc.j2
    dest: "{{ ansible_env.HOME }}/.kwm/kwmrc"
  notify: restart kwm

- name: khd dotfile
  template:
    src: khdrc.j2
    dest: "{{ ansible_env.HOME }}/.khdrc"
  notify: restart khd

- name: Start services
  command: brew services start {{ item }}
  register: start_service_result
  changed_when: "'already started' not in start_service_result.stdout"
  with_items:
    - khd
    - kwm

