
- name: Validate brew package config
  fail:
    msg: "Brew installation does not support versions"
  failed_when: item.value != None
  changed_when: false
  with_dict: "{{ packages.brew | default({}) }}"

- name: Install brew packages
  brew:
    name: "{{ item.key }}"
    state: latest
  with_dict: "{{ packages.brew | default({}) }}"

- name: Validate cask package config
  fail:
    msg: "Cask installation does not support versions"
  failed_when: item.value != None
  changed_when: false
  with_dict: "{{ packages.cask | default({}) }}"

- name: Install cask packages
  cask:
    name: "{{ item.key }}"
    state: latest
  with_dict: "{{ packages.cask | default({}) }}"

- name: Install pip packages
  pip:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
  with_dict: "{{ packages.pip | default({}) }}"

