
- name: Validate brew package config
  fail:
    msg: "Brew installation does not support versions"
  failed_when: item.version is defined
  changed_when: false
  with_items: "{{ packages.brew | default([]) }}"

- name: Install brew packages
  shell: "{{ brew_bin }} ls --versions {{ item.name }} || {{ brew_bin }} install {{ item.name }}"
  register: brew_install_result
  changed_when: brew_install_result.stdout.find(item.name) != 0
  with_items: "{{ packages.brew | default([]) }}"

- name: Install pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ packages.pip | default([]) }}"

