
- name: Install vim
  brew:
    name: vim
    state: latest

- name: Install MacVim
  cask:
    name: macvim
    state: latest

- name: .vimrc
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Checkout Pathogen
  git:
    repo: "{{ pathogen_repo }}"
    dest: "{{ pathogen_src_dir }}"
    version: "{{ pathogen_version }}"
  notify: update helptags

- name: Install Pathogen
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim"
    src: "{{ pathogen_src_dir }}/autoload/pathogen.vim"
    state: link
  notify: update helptags

- name: List installed plugins
  command: ls {{ vim_bundle_dir }}
  register: ls_vim_plugins
  changed_when: false

- name: Clear non-managed plugins
  file:
    state: absent
    path: "{{ vim_bundle_dir }}/{{ item }}"
  with_items: "{{ ls_vim_plugins.stdout_lines | difference(vim_plugins | map(attribute='repo') | map('basename')) }}"
  notify: update helptags

- name: Checkout Plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ vim_plugin_src_dir }}/{{ item.repo | basename }}"
    version: "{{ item.version }}"
  with_items: "{{ vim_plugins }}"
  notify: update helptags

- name: Install Plugins
  file:
    path: "{{ vim_bundle_dir }}/{{ item.repo | basename }}"
    src: "{{ vim_plugin_src_dir}}/{{ item.repo | basename }}"
    state: link
  with_items: "{{ vim_plugins }}"
  notify: update helptags

