
- name: Tap cask
  homebrew_tap:
    name: caskroom/cask
    state: present

- name: Verify cask installation
  command: "{{ cask_bin }} doctor"
  changed_when: false

- name: Update cask
  homebrew:
    update_homebrew: yes

